### PR TITLE
Change struct types but without fixing serialization.

### PR DESCRIPTION
**Pull request by jessebutterfield**
I had hoped to fix this in the upstream protobuf library but it actually turns out to be extremely tricky to fix all the different types of serialization, so I'm just hacking this in for now.

### CODE REVIEW

**Comment by sidraval** [comment]
Hey @jessebutterfield would you mind expanding a bit more on what we're doing and why? I'm sure we've talked about it before but my memory's not very good...

**Comment by jessebutterfield** [comment]
Structs have special json serialization rules so they are incorrectly rendered in typescript
Before
```ts
 export interface JsonReport {
   headers?: string[]
   rows?: Struct[]
 }
```
After
```ts
export interface JsonReport {
  headers?: string[]
  rows?: { [key: string]: any }[]
}
```

**Comment by jessebutterfield** [comment]
@sidraval Sorry, I have tendency to assign reviews before I finish commenting on them. Does that make it clearer?

**Review by sidraval — APPROVED** [review]
Out of curiosity, what did the prior `Struct` type look like?

**Pull request merged**
